### ISSUE TITLE
`entryOption` error when using with Rails Webpacker

### ISSUE THREAD

**Issue by osvaldasvalutis** [cascornelissen/svg-spritemap-webpack-plugin#28]
Using it with Rails Webpacker environment results in error:

```
TypeError: Cannot read property 'entryOption' of undefined
    at SVGSpritemapPlugin.apply (/some-project/node_modules/svg-spritemap-webpack-plugin/lib/index.js:73:24)
    at Compiler.apply (/some-project/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/some-project/node_modules/webpack/lib/webpack.js:33:19)
    at startDevServer (/some-project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:367:16)
    at processOptions (/some-project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:350:5)
    at Object.<anonymous> (/some-project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:495:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

...with this config:

```
const { environment } = require('@rails/webpacker');
const SVGSpritemapPlugin = require('svg-spritemap-webpack-plugin');

environment.plugins.prepend(
  'SVGSpritemapPlugin',
  new SVGSpritemapPlugin()
);

module.exports = environment;
```

Any ideas why?

**Comment by cascornelissen** [comment]
I'm guessing you're not running Webpack 4 but are using version `^2.0.0` of this plugin?

See https://github.com/cascornelissen/svg-spritemap-webpack-plugin/issues/25 for more information.
